### ISSUE TITLE
[BUG] TypeError: settings.blacklist?.forEach is not a function

### ISSUE THREAD

**Issue by ArjanSchoorl** [discord-tickets/bot#160]
**Describe the bug**
Getting the following error after installing the bot:
`2021-05-30 21:14:15 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
2021-05-30 21:14:15 [NOTICE] Discord Tickets v3.0.0, Node v14.17.0 on linux
2021-05-30 21:14:15 [WARN] An error was not caught
2021-05-30 21:14:15 [WARN] Uncaught TypeError
2021-05-30 21:14:15 [ERROR] TypeError: settings.blacklist?.forEach is not a function
at CommandManager.handle (/home/container/src/modules/commands/manager.js:83:24)
at processTicksAndRejections (internal/process/task_queues.js:95:5)`

**To reproduce**
Clean install, connect to mysql database, put bot information and start.

**Expected behaviour**
Not getting the error

**Screenshots**
![image](https://user-images.githubusercontent.com/23289492/120120391-33527400-c19d-11eb-97ba-2f51f972e0e9.png)

**Comment by eartharoid** [comment]
This has been fixed, download the code again.
