### ISSUE TITLE
[BUG] Can't close ticket if member left

### ISSUE THREAD

**Issue by whijio** [discord-tickets/bot#169]
**Describe the bug**
Running v3.0.0 of the bot, A member creates a ticket but then leaves the discord, upon closing the ticket I get the following error in the console: 

```
2021-06-05 05:58:13 [INFO] (COMMANDS) Executing "close" command (invoked by Whij#9001)
2021-06-05 05:58:16 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
2021-06-05 05:58:16 [NOTICE] Discord Tickets v3.0.0, Node v14.17.0 on linux
2021-06-05 05:58:16 [WARN] An error was not caught
2021-06-05 05:58:16 [WARN] Uncaught DiscordAPIError
2021-06-05 05:58:16 [ERROR] DiscordAPIError: Unknown Member
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async TicketManager.close (/home/container/src/modules/tickets/manager.js:262:20)
    at async ReactionCollector.<anonymous> (/home/container/src/commands/close.js:210:5)
```

**To reproduce**
Run v3.0.0 and have a user open a ticket, get them to leave discord and have a staff member try close their ticket

**Expected behavior**
I expect the bot to detect the player is not in the guild anymore and therefore just close the ticket

**Screenshots**
This is as far as the bot will take me before it errors
![image](https://user-images.githubusercontent.com/84020269/120861994-5a5adc80-c5c7-11eb-8339-2cce0f550232.png)

**Additional context**
None

**Comment by mon5termatt** [comment]
i just cant close it if they left....

**Comment by eartharoid** [comment]
Fixed in https://github.com/discord-tickets/bot/commit/5606071daac162944ffc36a3bc4d6814ffbc71a2
