### ISSUE TITLE
My index.js file creates a bunch of errors.

### ISSUE THREAD

**Issue by DonesCute** [discord-tickets/bot#191]
Getting this error, [ERROR] Error: Cryptr: secret must be a non-0-length string
    at new Cryptr (C:\Users\Dones\OneDrive\Desktop\New folder\bot-main\node_modules\cryptr\index.js:12:15)
    at C:\Users\Dones\OneDrive\Desktop\New folder\bot-main\src\index.js:135:18
    at new Bot (C:\Users\Dones\OneDrive\Desktop\New folder\bot-main\src\index.js:175:5)
    at Object.<anonymous> (C:\Users\Dones\OneDrive\Desktop\New folder\bot-main\src\index.js:202:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
_Originally posted by @DonesCute in https://github.com/discord-tickets/bot/discussions/190_

**Comment by eartharoid** [comment]
![image](https://user-images.githubusercontent.com/20905071/126831473-29633a04-1ba9-4910-b252-b25edbf2d302.png)

https://discordtickets.app/installation/#standard-installation

**Comment by DonesCute** [comment]
Still getting the same error message.

**Comment by eartharoid** [comment]
If you manually renamed `example.env` to `.env` you need to undo that and then follow the instructions.

**Comment by DonesCute** [comment]
I haven’t changed anything I have to files example.env and .env which I
made.

**Comment by DonesCute** [comment]
Never mind the bot is loading up as It created env file for me thank you so
much for the fast help.
