### ISSUE TITLE
[BUG] Table Error Postgresql

### ISSUE THREAD

**Issue by Y0ngg4n** [discord-tickets/bot#201]
Running Postgresql with Docker

```     

> @eartharoid/discord-tickets@3.0.0 start

> node src/


Copying "./user/example.config.js" to "./user/config.js"...

Copying "./example.env" to "./.env"...

Generating database encryption key...

Saved.

Warning: do not lose your ENV file or encryption key; you will lose access to data in the database.

Please set your bot's "DISCORD_TOKEN" in "./.env".


> @eartharoid/discord-tickets@3.0.0 start

> node src/



########  ####  ######   ######   #######  ########  ########

##     ##  ##  ##    ## ##    ## ##     ## ##     ## ##     ##

##     ##  ##  ##       ##       ##     ## ##     ## ##     ##

##     ##  ##   ######  ##       ##     ## ########  ##     ##

##     ##  ##        ## ##       ##     ## ##   ##   ##     ##

##     ##  ##  ##    ## ##    ## ##     ## ##    ##  ##     ##

########  ####  ######   ######   #######  ##     ## ########


######## ####  ######  ##    ## ######## ########  ######

   ##     ##  ##    ## ##   ##  ##          ##    ##    ##

   ##     ##  ##       ##  ##   ##          ##    ##

   ##     ##  ##       #####    ######      ##     ######

   ##     ##  ##       ##  ##   ##          ##          ##

   ##     ##  ##    ## ##   ##  ##          ##    ##    ##

   ##    ####  ######  ##    ## ########    ##     ######


Discord Tickets bot v3.0.0 by eartharoid

https://discordtickets.app


Sponsor this project (​https://discordtickets.app/sponsor​)


2021-08-13 11:55:41 [LOGGER] Initialising leekslazylogger (v3.0.2)

2021-08-13 11:55:41 [LOGGER] Preparing log files

2021-08-13 11:55:41 [LOGGER] No logs directory found, creating one for you

2021-08-13 11:55:41 [LOGGER] Fastify extension enabled

2021-08-13 11:55:41 [INFO] Connecting to PostgreSQL database...

2021-08-13 11:55:42 [SUCCESS] Connected to database successfully

2021-08-13 11:55:45 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:

2021-08-13 11:55:45 [NOTICE] Discord Tickets v3.0.0, Node v16.6.2 on linux

2021-08-13 11:55:45 [WARN] An error was not caught

2021-08-13 11:55:45 [WARN] Uncaught SequelizeDatabaseError

2021-08-13 11:55:45 [ERROR] SequelizeDatabaseError: there is no unique constraint matching given keys for referenced table "dsctickets_rootrole_entities"

    at Query.formatError (/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)

    at Query.run (/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async /node_modules/sequelize/lib/sequelize.js:619:16

    at async PostgresQueryInterface.createTable (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:225:12)

    at async Function.sync (/node_modules/sequelize/lib/model.js:1300:5)

    at async Sequelize.sync (/node_modules/sequelize/lib/sequelize.js:793:35)

    at async module.exports (/src/database/index.js:69:2)

    at async /src/index.js:153:14

```

**Comment by eartharoid** [comment]
I've only tested it with SQLite and MySQL. I'll try to fix this for the next release but for now you should use MySQL if you can.

**Comment by Y0ngg4n** [comment]
@eartharoid ok allright i will try mariadb
