### ISSUE TITLE
[BUG] Unexpected token "export" on startup

### ISSUE THREAD

**Issue by thephilluk** [discord-tickets/bot#216]
**Describe the bug**
Unexpected token "export" on startup

**To reproduce**
- Install via selfhost guide
- add Info to .env file (mysql on local machine)
- start with `npm start`
- get error shown below

**Expected behaviour**
Starting the Bot

**Log**
``` 2021-08-18 18:39:27 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
2021-08-18 18:39:27 [NOTICE] Discord Tickets v3.1.0-dev, Node v16.6.0 on linux
2021-08-18 18:39:27 [WARN] An error was not caught
2021-08-18 18:39:27 [WARN] Uncaught SyntaxError
2021-08-18 18:39:27 [ERROR] /home/theph/discord/bot/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/theph/discord/bot/node_modules/sequelize/lib/utils.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Comment by eartharoid** [comment]
Idk why you're getting that error, but it looks like you're not using a stable version of the bot which might not help.

![image](https://user-images.githubusercontent.com/20905071/129938405-5bae78c7-defd-445c-9482-9e5fad75815e.png)

**Comment by thephilluk** [comment]
Unfortunately still the same Error:

```2021-08-18 18:46:42 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
2021-08-18 18:46:42 [NOTICE] Discord Tickets v3.0.0, Node v16.6.0 on linux
2021-08-18 18:46:42 [WARN] An error was not caught
2021-08-18 18:46:42 [WARN] Uncaught SyntaxError
2021-08-18 18:46:42 [ERROR] /home/theph/discord/bot/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/theph/discord/bot/node_modules/sequelize/lib/utils.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

**Comment by thephilluk** [comment]
Found some Info on this:
https://github.com/uuidjs/uuid/issues/578

**Comment by thephilluk** [comment]
So far i have tried: 
- All major Node versions from 14 to 16
- add `"type": "module"` to the package.json as said [here[(https://support.glitch.com/t/cant-import-module-due-to-es6-syntax-unexpected-token-export/43057)

**Comment by eartharoid** [comment]
I'm not sure what is causing this. In the past, it was because someone was using Node <14 but you're not.

**Comment by thephilluk** [comment]
I'm installing Pterodactyl atm and will try via that.

**Comment by thephilluk** [comment]
still not working with pterodactyl, same issue.

**Comment by thephilluk** [comment]
We got it to work by redownloading it... i don't know how...
