### ISSUE TITLE
[BUG] [ERROR] DiscordAPIError: Invalid Form Body

### ISSUE THREAD

**Issue by vesturo** [discord-tickets/bot#246]
**Describe the bug**
An error occurred whilst publishing the commands

**To reproduce**
install latest on an clean nodejs installation

**Expected behaviour**
should work

**Screenshots**
none, full log at end

**Additional context**
it seems to be a problem with the new buttons and slash update

`11.options[0].name: This field is required
    at RequestHandler.execute (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ApplicationCommandManager.set (/root/bot/node_modules/discord.js/src/managers/ApplicationCommandManager.js:146:18)
    at async CommandManager.publish (/root/bot/src/modules/commands/manager.js:74:4)`

full log:
[error.txt](https://github.com/discord-tickets/bot/files/7289274/error.txt)

**Comment by eartharoid** [comment]
The translation feature is currently a bit broken. Use `en-GB` to avoid this error,
