### ISSUE TITLE
[BUG] [ERROR] DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by mrpiesel** [discord-tickets/bot#249]
**Describe the bug**

I cant start the bot

**Additional context**

Console:
2021-10-10 11:28:26 [LOGGER] Initialising leekslazylogger (v3.0.2)
2021-10-10 11:28:26 [LOGGER] Preparing log files
2021-10-10 11:28:27 [INFO] Using SQLite storage
2021-10-10 11:28:27 [WARN] Message logging is disabled due to insufficient database
2021-10-10 11:28:27 [SUCCESS] Connected to database successfully
2021-10-10 11:28:27 [INFO] Connecting to Discord API...
2021-10-10 11:28:28 [SUCCESS] Connected to Discord as "dclist.pl Private#9897"
2021-10-10 11:28:28 [INFO] Loading commands
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "add" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "blacklist" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "close" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "help" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "new" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "panel" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "remove" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "settings" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "stats" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "survey" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "tag" command
2021-10-10 11:28:28 [INFO] (COMMANDS) Loaded "topic" command
2021-10-10 11:28:28 [WARN] An error occurred whilst publishing the commands
2021-10-10 11:28:28 [ERROR] DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\MrPiesel\Desktop\bot-main\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\MrPiesel\Desktop\bot-main\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async ApplicationCommandManager.set (C:\Users\MrPiesel\Desktop\bot-main\bot-main\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18)
    at async CommandManager.publish (C:\Users\MrPiesel\Desktop\bot-main\bot-main\src\modules\commands\manager.js:74:5)

**Comment by eartharoid** [comment]
See [my reply](https://github.com/discord-tickets/bot/issues/244#issuecomment-929363317) to #244

**Comment by mrpiesel** [comment]
Thanks
