### ISSUE TITLE
[BUG] DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by Diego77648** [discord-tickets/bot#257]
**Describe the bug**

When I try to start the bot 
DiscordAPIError: Missing Access
This error pops out 

**To reproduce**
Thats a good question

**Expected behaviour**

**Screenshots**

2021-12-03 14:52:14 [WARN] An error occurred whilst publishing the commands
2021-12-03 14:52:14 [ERROR] DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\Users\mina1\Desktop\NorthTickets\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\mina1\Desktop\NorthTickets\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async ApplicationCommandManager.set (C:\Users\mina1\Desktop\NorthTickets\node_modules\discord.js\src\managers\ApplicationCommandManager.js:146:18)
    at async CommandManager.publish (C:\Users\mina1\Desktop\NorthTickets\src\modules\commands\manager.js:74:4)

Console Log

**Additional context**

**Comment by eartharoid** [comment]
> The bot needs permission to create application (slash) commands. Use the [invite URL generator ](https://discordtickets.app/invite-url-generator/)and add the bot to your Discord server again.
>
>https://discordtickets.app/faq/#discordapierror-missing-access
