### ISSUE TITLE
[BUG] MySQL when server start

### ISSUE THREAD

**Issue by mouse1121** [discord-tickets/bot#264]
Running MySQL on pterodactyl, server stuck and wan't start.

```container@panel4games~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@panel4games~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Digest: sha256:ec23ee8cb41993b6c44ce38e6b188a59848a910b0fa8baa007c502e220336399 
Status: Image is up to date for ghcr.io/parkervcp/yolks:nodejs_16 
[Pterodactyl Daemon]: Finished pulling Docker container image
v16.13.1
:/home/container$ if [[ ! -z ${VERSION} ]]; then echo -e \"Using version ${VERSION}\";else echo -e \"Please set the VERSION variable \(e.g. v3.1.1\)\"; exit 0;fi;if [[ -d .git ]]; then git fetch --all --tags; git checkout tags/${VERSION};fi;if [ -f /home/container/package.json ]; then /usr/local/bin/npm install --production;fi;if [[ ! -z ${PLUGINS} ]]; then /usr/local/bin/npm install ${PLUGINS} --no-save;fi;/usr/local/bin/npm start
"Using version v3.1.3"
Fetching origin
M       src/database/models/guild.model.js
M       src/logger.js
HEAD is now at 8897602 build: bump version

up to date, audited 196 packages in 4s

17 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 341 packages, and audited 537 packages in 9s

54 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> @eartharoid/discord-tickets@3.1.3 start
> node src/


########  ####  ######   ######   #######  ########  ########
##     ##  ##  ##    ## ##    ## ##     ## ##     ## ##     ##
##     ##  ##  ##       ##       ##     ## ##     ## ##     ##
##     ##  ##   ######  ##       ##     ## ########  ##     ##
##     ##  ##        ## ##       ##     ## ##   ##   ##     ##
##     ##  ##  ##    ## ##    ## ##     ## ##    ##  ##     ##
########  ####  ######   ######   #######  ##     ## ########

######## ####  ######  ##    ## ######## ########  ######
   ##     ##  ##    ## ##   ##  ##          ##    ##    ##
   ##     ##  ##       ##  ##   ##          ##    ##
   ##     ##  ##       #####    ######      ##     ######
   ##     ##  ##       ##  ##   ##          ##          ##
   ##     ##  ##    ## ##   ##  ##          ##    ##    ##
   ##    ####  ######  ##    ## ########    ##     ######

Discord Tickets bot v3.1.3 by eartharoid
https://discordtickets.app

Sponsor this project (​https://discordtickets.app/sponsor​)

2022-01-11 19:45:14 [LOGGER] Initialising leekslazylogger (v3.0.2)
2022-01-11 19:45:14 [LOGGER] Preparing log files
2022-01-11 19:45:15 [INFO] Connecting to MySQL database...
2022-01-11 19:45:15 [SUCCESS] Connected to database successfully
2022-01-11 19:45:15 [NOTICE] PLEASE INCLUDE THIS INFORMATION IF YOU ASK FOR HELP ABOUT THE FOLLOWING ERROR:
2022-01-11 19:45:15 [NOTICE] Discord Tickets v3.1.3, Node v16.13.1 on linux
2022-01-11 19:45:15 [WARN] An error was not caught
2022-01-11 19:45:15 [WARN] Uncaught SequelizeDatabaseError
2022-01-11 19:45:15 [ERROR] Error
    at Query.run (/home/container/node_modules/sequelize/dist/lib/dialects/mysql/query.js:52:25)
    at /home/container/node_modules/sequelize/dist/lib/sequelize.js:313:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.createTable (/home/container/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:94:12)
    at async Function.sync (/home/container/node_modules/sequelize/dist/lib/model.js:930:5)
    at async Sequelize.sync (/home/container/node_modules/sequelize/dist/lib/sequelize.js:377:9)
    at async module.exports (/home/container/src/database/index.js:70:2)
    at async /home/container/src/index.js:160:14```

**Comment by eartharoid** [comment]
Sequelize's errors aren't very helpful :|

**Comment by mouse1121** [comment]
> Sequelize's errors aren't very helpful :|

And what to do?

**Comment by eartharoid** [comment]
I'm guessing you need to update MySQL.

**Comment by RooRay** [comment]
this shouldnt really be an issue and more of just a support query as this seems to be a genuine issue with your setup of the bot, not its code
