### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by WooAf** [discord-tickets/bot#271]
**Describe the bug**
Opening a ticket throw an error

**To reproduce**
Open a ticket from a panel

```
2022-02-03 11:52:00 [ERROR] DiscordAPIError: Invalid Form Body
name: Contains words not allowed for servers in Server Discovery.
    at RequestHandler.execute (O:\DiscordBot\TicketSupport\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (O:\DiscordBot\TicketSupport\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async GuildChannelManager.create (O:\DiscordBot\TicketSupport\node_modules\discord.js\src\managers\GuildChannelManager.js:152:18)
    at async TicketManager.create (O:\DiscordBot\TicketSupport\src\modules\tickets\manager.js:53:21)
    at async handlePanel (O:\DiscordBot\TicketSupport\src\listeners\interactionCreate.js:93:20)
```

![image](https://user-images.githubusercontent.com/6692090/152389764-d0008727-9958-4928-a188-565027ac3ff2.png)

**Comment by eartharoid** [comment]
Do you have over 1400 tickets?

**Comment by eartharoid** [comment]
#262

**Comment by WooAf** [comment]
How I can skip 1488 ?

**Comment by eartharoid** [comment]
Create a row in the `tickets` database table with the number `1488`. Make sure you include the guild and user id etc
