### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PascaliRBX** [discord-tickets/bot#326]
Everytime i started the Bot this error occured.

[ERROR] DiscordAPIError: Invalid Form Body
0.options[0].name: Command name is invalid
9.options[0].name: Command name is invalid
    at RequestHandler.execute (C:\Users\Pascal\Downloads\bot-main\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Pascal\Downloads\bot-main\bot-main\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ApplicationCommandManager.set (C:\Users\Pascal\Downloads\bot-main\bot-main\node_modules\discord.js\src\managers\ApplicationCommandManager.js:162:18)
    at async CommandManager.publish (C:\Users\Pascal\Downloads\bot-main\bot-main\src\modules\commands\manager.js:74:4)

i dont change the commands

**Comment by eartharoid** [comment]
Did you change the `locale` in the `config.js file?`

**Comment by PascaliRBX** [comment]
I change the locale in German this dont work, i set it back to english now. Now i tried to create a category but it dont work, does not react idk whats the problem

**Comment by eartharoid** [comment]
You can change the locale for your server with `/settings set locale: de-DE`.

Could you [join the support server](https://lnk.earth/discord) so I can help with the other problem?

**Comment by PascaliRBX** [comment]
yes thx :)
