### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by samrudd** [discord-tickets/bot#332]
when i sgtart the bot i get this

2022-09-04 12:07:45 [SUCCESS] Published 12 commands to "Server"
2022-09-04 12:07:46 [WARN] An error occurred whilst updating command permissions
2022-09-04 12:07:46 [ERROR] DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ApplicationCommandPermissionsManager.set (/home/container/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:186:18)
    at async /home/container/src/modules/commands/manager.js:137:5

the bot is working but i wanted to check on this error.

also how do i recall the historic tickets for future reference

**Comment by eartharoid** [comment]
You can ignore that error.

> also how do i recall the historic tickets for future reference

Use https://discordtickets.app/plugins/official/text-transcripts for this.
Much better solution coming soon.
