### ISSUE TITLE
[BUG] ExpectedConstraintError when running most slash commands, messaging the bot directly or clicking the create button on a deployed panel

### ISSUE THREAD

**Issue by thecmdradama** [discord-tickets/bot#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to run various slash commands or use the buttons on the deployed panel, I get the following from the bot's console.

The error when using the create button
```
[ERROR] (BUTTONS) "create" button execution error: ExpectedConstraintError > s.array(T).lengthGreaterThanOrEqual
  Invalid Array length

  Expected: expected.length >= 1

  Received:
  | []

    at Object.run (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:267:79)
    at /var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:66
    at Array.reduce (<anonymous>)
    at ArrayValidator.parse (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:29)
    at validateRequiredParameters (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:840:23)
    at ModalBuilder.toJSON (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:873:5)
    at ButtonInteraction.showModal (/var/lib/pufferpanel/servers/abb7ee01/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:256:46)
    at TicketManager.create (/var/lib/pufferpanel/servers/abb7ee01/src/lib/tickets/manager.js:252:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CreateButton.run (/var/lib/pufferpanel/servers/abb7ee01/src/buttons/create.js:16:3)
```

The error when using the new slash command
```
[ERROR] (COMMANDS) "new" command execution error: ExpectedConstraintError > s.array(T).lengthGreaterThanOrEqual
  Invalid Array length

  Expected: expected.length >= 1

  Received:
  | []

    at Object.run (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:267:79)
    at /var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:66
    at Array.reduce (<anonymous>)
    at ArrayValidator.parse (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:29)
    at validateRequiredParameters (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:840:23)
    at ModalBuilder.toJSON (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:873:5)
    at ChatInputCommandInteraction.showModal (/var/lib/pufferpanel/servers/abb7ee01/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:256:46)
    at TicketManager.create (/var/lib/pufferpanel/servers/abb7ee01/src/lib/tickets/manager.js:252:22)
    at async useGuild (/var/lib/pufferpanel/servers/abb7ee01/src/lib/tickets/utils.js:41:4)
    at async NewSlashCommand.run (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/new.js:36:3)
```
The error when attempting to create a ticket with a direct message to the bot 
```
[ERROR] ExpectedConstraintError > s.array(T).lengthGreaterThanOrEqual
  Invalid Array length

  Expected: expected.length >= 1

  Received:
  | []

    at Object.run (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:267:79)
    at /var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:66
    at Array.reduce (<anonymous>)
    at ArrayValidator.parse (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@sapphire/shapeshift/dist/index.js:201:29)
    at validateRequiredParameters (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:840:23)
    at ModalBuilder.toJSON (/var/lib/pufferpanel/servers/abb7ee01/node_modules/@discordjs/builders/dist/index.js:873:5)
    at ButtonInteraction.showModal (/var/lib/pufferpanel/servers/abb7ee01/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:256:46)
    at TicketManager.create (/var/lib/pufferpanel/servers/abb7ee01/src/lib/tickets/manager.js:252:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.useGuild (/var/lib/pufferpanel/servers/abb7ee01/src/listeners/client/messageCreate.js:45:4)
```

### Expected Behavior

The expected behaviour is for the bot to respond that it has created and a new channel is spawned for the new ticket.

### Steps To Reproduce

For slash commands
1. In Discord server run the `/new` slash command
2. The bot returns the following on Discord
![Screenshot 2023-02-06 151328](https://user-images.githubusercontent.com/44428944/216907242-291ae0f1-475b-49f2-b637-969ba36dc9f1.png)
and the previously referred to error is found in the console logs

For slash commands
1. In Discord, navigate to the channel where the panel has been deployed
2. Click the button "Create a ticket".
3. The bot returns the following on Discord
![Screenshot 2023-02-06 151328](https://user-images.githubusercontent.com/44428944/216907242-291ae0f1-475b-49f2-b637-969ba36dc9f1.png)
and the previously referred to error is found in the console logs

For Direct messages,
1. In Discord, direct message the bot anything. 
![Screenshot 2023-02-06 151647](https://user-images.githubusercontent.com/44428944/216907786-177ab93c-f097-4941-90fb-c45557e7231e.png)
2. Click the "Create Ticket button".
3. the above window disappears. and the previously referred to error is found in the console logs

### Environment

```markdown
- OS: Ubuntu 22.04.1
- Node: 18.14.0 LTS
- NPM: 9.3.1
- Bot: v4.0.0-beta.3
```

**Comment by eartharoid** [comment]
@thecmdradama could you share configuration details (a screenshot of the settings panel) for the category you are trying to create a ticket in, specifically the opening questions?

From these errors, I'm assuming you have added questions but they are all menu, not text type.
Menu questions are fully working in the settings panel but are not supported by Discord modals currently, so deleting the questions should solve this problem.
