### ISSUE TITLE
[BUG] TypeError: channel.isText is not a function

### ISSUE THREAD

**Issue by Netherwhal** [discord-tickets/bot#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Bot stopped working:

```
/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:48
        if (channel && !channel.isText()) return;
                                ^

TypeError: channel.isText is not a function
    at InteractionCreateAction.handle (/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:48:33)
    at Object.module.exports [as INTERACTION_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:493:22)
    at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:327:10)
    at callListener (/app/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
```

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by eartharoid** [comment]
This was caused by a change to the Discord API and can be fixed by updating `discord.js` to version `13.14.0`.

Copied from the [discord.js FAQ](https://discord.com/channels/222078108977594368/769862166131245066/1090766967302008872):

---

<strong>TypeError <code class="inline">channel.isTextBased is not a function</code> / <code class="inline">channel.isText is not a function</code></strong>
 • <code class="inline">v14</code>: <code class="inline">npm i discord.js@latest</code>
 • <code class="inline">v13</code>: <code class="inline">npm i discord.js@v13-lts</code>
 • If you are using a process* manager (like PM2), make sure to <u>restart the daemon process</u>!

<strong>What happened?</strong>
<div class="blockquoteContainer-3VtvI1"><div class="blockquoteDivider-363utW"></div><blockquote>Discord has rolled out a change which broke how we handle things in discord.js. We have fixed this when it first came up and was reverted due to breaking a lot of bots without an immediate fix. Apparently you have not updated discord.js since we did that!
</blockquote></div>
<strong>How do I fix it?</strong>
<div class="blockquoteContainer-3VtvI1"><div class="blockquoteDivider-363utW"></div><blockquote>Update discord.js! <em>(updating minor versions should not break anything)</em>
</blockquote></div>
<strong>But I didn't change anything!</strong>
<div class="blockquoteContainer-3VtvI1"><div class="blockquoteDivider-363utW"></div><blockquote>Correct, but Discord did! <em>(and as response discord.js did, which you need to apply now)</em>
</blockquote></div>
<strong>I updated and it still throws this error!</strong>
<div class="blockquoteContainer-3VtvI1"><div class="blockquoteDivider-363utW"></div><blockquote>•  Please make sure you actually updated the library and confirm the version with <code class="inline">npm list discord.js</code>

•  You need to have a version of at least <code class="inline">14.8.0</code> or <code class="inline">13.14.0</code> respectively.
</blockquote></div>
<strong>It shows the right version number, but still throws this error!</strong>
<div class="blockquoteContainer-3VtvI1"><div class="blockquoteDivider-363utW"></div><blockquote>Try a clean installation with your package manager of choice:
<em>(again, make sure you restart the daemon process, if you are using a process manager!)</em>
</blockquote></div>
V14:

```
npm remove discord.js
npm install discord.js

yarn remove discord.js
yarn add discord.js

pnpm remove discord.js
pnpm install discord.js
```

V13:
```
npm remove discord.js
npm install discord.js@13

yarn remove discord.js
yarn add discord.js@13

pnpm remove discord.js
pnpm install discord.js@13
```

If after this you still get this error, please open a post in our support forum with a full error stack trace and your relevant code!
