### ISSUE TITLE
[BUG] DiscordAPIError[50013]: Missing Permissions

### ISSUE THREAD

**Issue by Netherwhal** [discord-tickets/bot#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
 01/07/23 23:37:42  [ERROR] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/.pnpm/@discordjs+rest@1.7.1/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/.pnpm/@discordjs+rest@1.7.1/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/.pnpm/@discordjs+rest@1.7.1/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/container/node_modules/.pnpm/@discordjs+rest@1.7.1/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async Guild.fetchAuditLogs (/home/container/node_modules/.pnpm/discord.js@14.11.0_bufferutil@4.0.7_utf-8-validate@5.0.10/node_modules/discord.js/src/structures/Guild.js:759:18)
    at async module.exports.run (/home/container/src/listeners/client/messageDelete.js:33:21) {
  requestBody: { files: undefined, json: undefined },
  **rawError: { message: 'Missing Permissions', code: 50013 },**
  code: 50013,
  status: 403,
  method: 'GET',
  url: 'https://discord.com/api/v10/guilds//audit-logs?limit=1&action_type=72'
```

seems like a race condition? Does not always happen and things still work.

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot:
```

**Comment by RooRay** [comment]
Are you sure this isn't an issue with the permissions you have assigned the bot in your Discord server? If not please give steps to reproduce

**Comment by Netherwhal** [comment]
It happens intermittent, hence why I think race condition. Otherwise it works so perms are there

**Comment by eartharoid** [comment]
https://discordjs.guide/popular-topics/permissions-extended.html#missing-permissions
still have no idea
