### ISSUE TITLE
[BUG] Fails to register commands on every start

### ISSUE THREAD

**Issue by TheBoiCJ** [discord-tickets/bot#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The bot will fail to register slash commands on boot.

### Expected Behavior

It registering the commands.

### Steps To Reproduce

1. Follow the guide
2. Run the bot
3. Error

### Environment

```markdown
- OS: Ubuntu 22.04
- Node: v20.18.0
- NPM: 10.8.2
- Bot: latest
```

### Anything else?

```log
DiscordAPIError[50035]: Invalid Form Body
3.name_localizations[STRING_TYPE_REGEX]: String value did not match validation regex.
    at handleErrors (/root/CTickets/node_modules/.pnpm/@discordjs+rest@2.4.0/node_modules/@discordjs/rest/dist/index.js:727:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/root/CTickets/node_modules/.pnpm/@discordjs+rest@2.4.0/node_modules/@discordjs/rest/dist/index.js:1128:23)
    at async SequentialHandler.queueRequest (/root/CTickets/node_modules/.pnpm/@discordjs+rest@2.4.0/node_modules/@discordjs/rest/dist/index.js:959:14)
    at async _REST.request (/root/CTickets/node_modules/.pnpm/@discordjs+rest@2.4.0/node_modules/@discordjs/rest/dist/index.js:1272:22)
    at async ApplicationCommandManager.set (/root/CTickets/node_modules/.pnpm/discord.js@14.16.3_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/discord.js/src/managers/ApplicationCommandManager.js:171:18) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ]
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { '3': [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/1308341374810198037/commands'
}
```

**Comment by eartharoid** [comment]
Use the [latest release](https://github.com/discord-tickets/bot/releases/latest) rather than the main branch.

**Comment by TheBoiCJ** [comment]
Thanks
