### ISSUE TITLE
[BUG] Timed out during query execution

### ISSUE THREAD

**Issue by JHubi1** [discord-tickets/bot#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes the bot sends a message "⚠️ Something went wrong" and the console shows the following output:

```
 26/11/24 21:05:59  [ERROR] (PRISMA) ticket.update 
Invalid `prisma.ticket.update()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
 26/11/24 21:05:59  [ERROR] (BUTTONS) 67463837M0
 26/11/24 21:05:59  [ERROR] (MODALS) "feedback" modal execution error: PrismaClientUnknownRequestError: 
Invalid `prisma.ticket.update()` invocation:
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
    at Rn.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/@prisma/client/runtime/library.js:174:7499)
    at Rn.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/app/node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/@prisma/client/runtime/library.js:174:6344)
    at async module.exports (/app/src/lib/middleware/prisma-sqlite.js:44:15)
    at async FeedbackModal.run (/app/src/modals/feedback.js:34:18) {
  clientVersion: '4.16.2'
}
```

### Expected Behavior

Working

### Steps To Reproduce

Could not reliably reproduce. But often happens when using the /claim and /close command (which soft locks the ticket)

### Environment

```markdown
- OS: Docker image
```

### Anything else?

I use the sqlite database, because it's easier for me to manage

**Comment by eartharoid** [comment]
This might indicate that your bot is too active for SQLite to keep up, and you should switch to MySQL or PostgreSQL.

**Comment by RooRay** [comment]
this is likely an issue related to your database being too slow - if you're on pterodactyl/pelican use an included database or [this guide](https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-22-04-quickstart) for postgresql on a vps (assuming you use ubuntu)
